[package]
name = "waccesstop"
version = "0.2.0"
authors = ["b.couloigner <b.couloigner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.5"
clap = {features = ["yaml"]}
flate2 = "1.0.4"
