name: GitHub Actions Demo new
run-name: ${{ github.actor }} is testing out GitHub Actions new 🚀
on:
  pull_request_target:
    types: [opened, closed, synchronize, reopened]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
